FROM python:3.14-slim

WORKDIR /backend

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["python", "-m", "uvicorn", "app.app:app"]

CMD ["--host", "0.0.0.0", "--port", "8000", "--reload"]