"""update table projectmember and assigned_tasks  for user cascade delete

Revision ID: 02430dd3feb3
Revises: 27790874a60e
Create Date: 2026-09-21 17:10:00.890932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02430dd3feb3'
down_revision: Union[str, Sequence[str], None] = '27790874a60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
