"""update table activity log for ondelete

Revision ID: 36750df25fa9
Revises: ced5deac62fb
Create Date: 2026-09-21 17:01:01.411286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36750df25fa9'
down_revision: Union[str, Sequence[str], None] = 'ced5deac62fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_log_user_id_fkey'), 'activity_log', type_='foreignkey')
    op.drop_constraint(op.f('activity_log_project_id_fkey'), 'activity_log', type_='foreignkey')
    op.drop_constraint(op.f('activity_log_task_id_fkey'), 'activity_log', type_='foreignkey')
    op.create_foreign_key(None, 'activity_log', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_log', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.create_foreign_key(op.f('activity_log_task_id_fkey'), 'activity_log', 'task', ['task_id'], ['id'])
    op.create_foreign_key(op.f('activity_log_project_id_fkey'), 'activity_log', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('activity_log_user_id_fkey'), 'activity_log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
