"""update table projectmember and assigned_tasks  for user cascade delete 2

Revision ID: a10d217cbedb
Revises: 02430dd3feb3
Create Date: 2026-09-21 17:13:01.896197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10d217cbedb'
down_revision: Union[str, Sequence[str], None] = '02430dd3feb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_creator_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_creator_id_fkey'), 'task', 'user', ['creator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
